Repository NBCampArchive/Oripresso, pull requests merged in 2024-04, with the labels that each got.

#6 [Feat] 메인페이지 기본 틀
  Oripresso.xcodeproj/project.pbxproj
  Oripresso/Assets.xcassets/cart.imageset/Contents.json
  Oripresso/Assets.xcassets/cart.imageset/humbleicons_cart.svg
  Oripresso/Assets.xcassets/greenCircle.imageset/Contents.json
  Oripresso/Assets.xcassets/greenCircle.imageset/Ellipse 19.svg
  Oripresso/Assets.xcassets/menuSelectBottom.imageset/Contents.json
  Oripresso/Assets.xcassets/menuSelectBottom.imageset/menuSelectBottom.svg
  Oripresso/Assets.xcassets/orangeCircle.imageset/Contents.json
  Oripresso/Assets.xcassets/orangeCircle.imageset/Ellipse 7.svg
  Oripresso/Assets.xcassets/title.imageset/Contents.json
  Oripresso/Assets.xcassets/title.imageset/title.svg
  Oripresso/Base.lproj/Main.storyboard
  Oripresso/Info.plist
  Oripresso/MainView.storyboard
  Oripresso/MainViewController.swift
Labels: Feature

#7 [Feat] 주문내역 뷰 UI 구현
  Oripresso.xcodeproj/project.pbxproj
  Oripresso/Assets.xcassets/OripressoTitle.imageset/Contents.json
  Oripresso/Assets.xcassets/OripressoTitle.imageset/OripressoTitle.svg
  Oripresso/Assets.xcassets/location_pay.imageset/Contents.json
  Oripresso/Assets.xcassets/location_pay.imageset/Group 6.svg
  Oripresso/Assets.xcassets/orderListTitleText.imageset/Contents.json
  Oripresso/Assets.xcassets/orderListTitleText.imageset/orderListTitleText.svg
  Oripresso/Assets.xcassets/titleBar.imageset/Contents.json
  Oripresso/Assets.xcassets/titleBar.imageset/titleBar.svg
  Oripresso/Assets.xcassets/totalBar.imageset/Contents.json
  Oripresso/Assets.xcassets/totalBar.imageset/totalBar.svg
  Oripresso/Base.lproj/Main.storyboard
  Oripresso/OrderList.storyboard
Labels: Feature

#9 [Design] Segment, Cell 추가 및 Constraints 수정 #5
  Oripresso/MainView.storyboard
  Oripresso/MainViewController.swift
  Oripresso/OrderList.storyboard
Labels: Feature

#12 [Feat] 주문내역 뷰 디자인 수정 및 테이블뷰 기능 구현 완료
  Oripresso.xcodeproj/project.pbxproj
  Oripresso/Assets.xcassets/minus.imageset/Contents.json
  Oripresso/Assets.xcassets/minus.imageset/minus.svg
  Oripresso/Assets.xcassets/plus.imageset/Contents.json
  Oripresso/Assets.xcassets/plus.imageset/plus.svg
  Oripresso/Base.lproj/LaunchScreen.storyboard
  Oripresso/OrderList.storyboard
  Oripresso/OrderListTableViewCell.swift
  Oripresso/OrderListViewController.swift
Labels: Feature

#13 Feat/alert alert알림창 구현
  Oripresso.xcodeproj/project.pbxproj
  Oripresso/OrderList.storyboard
  Oripresso/orderButtonViewController.swift
Labels: Feature

#15 [Design] Menu TableView & TableCell Design Update
  Oripresso.xcodeproj/project.pbxproj
  Oripresso.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Oripresso/Assets.xcassets/americano.imageset/Contents.json
  Oripresso/Assets.xcassets/americano.imageset/icedAmericano.svg
  Oripresso/MainView.storyboard
  Oripresso/MainViewController.swift
  Oripresso/MainViewTableCell.swift
Labels: Design

#17 [Feat] 주문내역 - 테이블뷰 구현 완료(셀 삭제 기능, 가격 천 단위 콤마)
  Oripresso.xcodeproj/project.pbxproj
  Oripresso.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Oripresso/OrderList.storyboard
  Oripresso/OrderListTableViewCell.swift
  Oripresso/OrderListViewController.swift
  Podfile
Labels: Feature

#18 [Feat] Navigation, 장바구니, 멀티 선택 기능 구현
  Oripresso/Assets.xcassets/selectedLabelImage.imageset/Contents.json
  Oripresso/Assets.xcassets/selectedLabelImage.imageset/Ellipse 23.svg
  Oripresso/MainView.storyboard
  Oripresso/MainViewController.swift
  Oripresso/OrderList.storyboard
Labels: Feature

#19 [Feat] MenuData Json & Struct File, parse into MenuTable Cell
  Oripresso.xcodeproj/project.pbxproj
  Oripresso/CoffeeMenu.swift
  Oripresso/MainViewController.swift
  Oripresso/MainViewTableCell.swift
  Oripresso/en.lproj/CoffeeJson.json
Labels: Feature

#22 [Feat] Navigation With SelectedMenuData
  Oripresso.xcodeproj/project.pbxproj
  Oripresso.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Oripresso/MainViewController.swift
  Oripresso/MainViewTableCell.swift
Labels: Feature

#20 [Feat] 주문내역 뷰 - 총 수량&가격 업데이트, 주문취소 액션 설정
  Oripresso.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Oripresso/OrderList.storyboard
  Oripresso/OrderListViewController.swift
Labels: Feature

#24 [Feat] Infinite Scroll & ActivityIndicator
  Oripresso.xcodeproj/project.pbxproj
  Oripresso.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Oripresso/CoffeeMenu.swift
  Oripresso/MainViewController.swift
  Oripresso/MainViewTableCell.swift
  Oripresso/OrderListViewController.swift
  Oripresso/SelectedMenu.swift
  Oripresso/en.lproj/CoffeeJson.json
Labels: Feature

#27 [Feat] 결제완료 페이지
  .github/pull_request_template.md
  Oripresso.xcodeproj/project.pbxproj
  Oripresso/Assets.xcassets/receipt.imageset/Contents.json
  Oripresso/Assets.xcassets/receipt.imageset/receipt.pdf
  Oripresso/Assets.xcassets/underBar.imageset/Contents.json
  Oripresso/Assets.xcassets/underBar.imageset/underBar.svg
  Oripresso/Base.lproj/Main.storyboard
  Oripresso/Fonts/NanumSquareRoundB.ttf
  Oripresso/Fonts/NanumSquareRoundEB.ttf
  Oripresso/Fonts/NanumSquareRoundL.ttf
  Oripresso/Fonts/NanumSquareRoundR.ttf
  Oripresso/Info.plist
  Oripresso/Payment.storyboard
  Oripresso/Payments.swift
  README.md
Labels: Feature

#30 [Feat] Payment & Launch Screen 연결
  Oripresso.xcodeproj/project.pbxproj
  Oripresso/AppDelegate.swift
  Oripresso/Assets.xcassets/launchBackground.imageset/Contents.json
  Oripresso/Base.lproj/LaunchScreen.storyboard
  Oripresso/Info.plist
  Oripresso/MainViewController.swift
  Oripresso/MainViewTableCell.swift
  Oripresso/OrderList.storyboard
  Oripresso/OrderListTableViewCell.swift
  Oripresso/OrderListViewController.swift
  Oripresso/Payment.storyboard
  Oripresso/Payments.swift
  Oripresso/PaymentsViewController.swift
Labels: BugFix, Feature

#32 [Feat] OrderList에서 MainView로 이동할 때 selectedMenu 데이터 전달, dessert 오타 수정
  Oripresso/CoffeeMenu.swift
  Oripresso/MainView.storyboard
  Oripresso/MainViewController.swift
  Oripresso/OrderListViewController.swift
  Oripresso/en.lproj/CoffeeJson.json
Labels: Feature

#34 [Fix] 처음 Coffee 메뉴를 불러올 때 2번 불러오는 오류 수정
  Oripresso/MainViewController.swift
Labels: BugFix

#36 [Chore] MVC Folder Directory
  Oripresso.xcodeproj/project.pbxproj
  Oripresso/Controllers/MainViewController.swift
  Oripresso/Controllers/OrderListViewController.swift
  Oripresso/Controllers/PaymentsViewController.swift
  Oripresso/Models/CoffeeMenu.swift
  Oripresso/Models/SelectedMenu.swift
  Oripresso/Models/en.lproj/CoffeeJson.json
  Oripresso/Views/Base.lproj/LaunchScreen.storyboard
  Oripresso/Views/Base.lproj/Main.storyboard
  Oripresso/Views/MainView.storyboard
  Oripresso/Views/MainViewTableCell.swift
  Oripresso/Views/OrderList.storyboard
  Oripresso/Views/OrderListTableViewCell.swift
  Oripresso/Views/Payment.storyboard
Labels: Setting

#38 [Feat] 시작화면 디자인
  Oripresso.xcodeproj/project.pbxproj
  Oripresso/Assets.xcassets/Members/Contents.json
  Oripresso/Assets.xcassets/Members/ryeol.imageset/Contents.json
  Oripresso/Assets.xcassets/Members/ryeol.imageset/ryeol.png
  Oripresso/Assets.xcassets/Members/seunghyeon.imageset/Contents.json
  Oripresso/Assets.xcassets/Members/seunghyeon.imageset/senghyun.png
  Oripresso/Assets.xcassets/Members/sian.imageset/Contents.json
  Oripresso/Assets.xcassets/Members/sian.imageset/sian.png
  Oripresso/Assets.xcassets/Members/slowgeon.imageset/Contents.json
  Oripresso/Assets.xcassets/Members/slowgeon.imageset/slowgeon.png
  Oripresso/Assets.xcassets/Members/yurim.imageset/Contents.json
  Oripresso/Assets.xcassets/Members/yurim.imageset/yurim.png
  Oripresso/Assets.xcassets/post/Contents.json
  Oripresso/Assets.xcassets/post/post1.imageset/Contents.json
  Oripresso/Assets.xcassets/post/post1.imageset/post1.png
  Oripresso/Assets.xcassets/post/post2.imageset/Contents.json
  Oripresso/Assets.xcassets/post/post2.imageset/post2.png
  Oripresso/Assets.xcassets/post/post3.imageset/Contents.json
  Oripresso/Assets.xcassets/post/post3.imageset/post3.png
  Oripresso/Assets.xcassets/post/post4.imageset/Contents.json
  Oripresso/Assets.xcassets/post/post4.imageset/post4.png
  Oripresso/Controllers/MainViewController.swift
  Oripresso/Controllers/OnboardViewController.swift
  Oripresso/Info.plist
  Oripresso/Models/CrewMember.swift
  Oripresso/Views/CrewCollectionCell.swift
  Oripresso/Views/MainView.storyboard
  Oripresso/Views/Onboard.storyboard
  Oripresso/Views/PostCollectionCell.swift
Labels: Feature

#39 [Feat] MainBranch 최신화
  Oripresso.xcodeproj/project.pbxproj
  Oripresso/Assets.xcassets/Members/Contents.json
  Oripresso/Assets.xcassets/Members/ryeol.imageset/Contents.json
  Oripresso/Assets.xcassets/Members/ryeol.imageset/ryeol.png
  Oripresso/Assets.xcassets/Members/seunghyeon.imageset/Contents.json
  Oripresso/Assets.xcassets/Members/seunghyeon.imageset/senghyun.png
  Oripresso/Assets.xcassets/Members/sian.imageset/Contents.json
  Oripresso/Assets.xcassets/Members/sian.imageset/sian.png
  Oripresso/Assets.xcassets/Members/slowgeon.imageset/Contents.json
  Oripresso/Assets.xcassets/Members/slowgeon.imageset/slowgeon.png
  Oripresso/Assets.xcassets/Members/yurim.imageset/Contents.json
  Oripresso/Assets.xcassets/Members/yurim.imageset/yurim.png
  Oripresso/Assets.xcassets/post/Contents.json
  Oripresso/Assets.xcassets/post/post1.imageset/Contents.json
  Oripresso/Assets.xcassets/post/post1.imageset/post1.png
  Oripresso/Assets.xcassets/post/post2.imageset/Contents.json
  Oripresso/Assets.xcassets/post/post2.imageset/post2.png
  Oripresso/Assets.xcassets/post/post3.imageset/Contents.json
  Oripresso/Assets.xcassets/post/post3.imageset/post3.png
  Oripresso/Assets.xcassets/post/post4.imageset/Contents.json
  Oripresso/Assets.xcassets/post/post4.imageset/post4.png
  Oripresso/Controllers/MainViewController.swift
  Oripresso/Controllers/OnboardViewController.swift
  Oripresso/Controllers/OrderListViewController.swift
  Oripresso/Controllers/PaymentsViewController.swift
  Oripresso/Info.plist
  Oripresso/Models/CoffeeMenu.swift
  Oripresso/Models/CrewMember.swift
  Oripresso/Models/SelectedMenu.swift
  Oripresso/Models/en.lproj/CoffeeJson.json
  Oripresso/Views/Base.lproj/LaunchScreen.storyboard
  Oripresso/Views/Base.lproj/Main.storyboard
  Oripresso/Views/CrewCollectionCell.swift
  Oripresso/Views/MainView.storyboard
  Oripresso/Views/MainViewTableCell.swift
  Oripresso/Views/Onboard.storyboard
  Oripresso/Views/OrderList.storyboard
  Oripresso/Views/OrderListTableViewCell.swift
  Oripresso/Views/Payment.storyboard
  Oripresso/Views/PostCollectionCell.swift
Labels: Feature

#40 [Fix] view 계층구조 변경에 따른 에러 수정
  Oripresso/Controllers/OrderListViewController.swift
  Oripresso/Models/en.lproj/CoffeeJson.json
Labels: BugFix

#41 fix - 총 수량 미변경 이슈 해결
  Oripresso/Controllers/OrderListViewController.swift
Labels: BugFix
